database {
  host = "localhost"
  host = ${?DATABASE_HOST}
  port = 5432
  port = ${?DATABASE_PORT}
  name = "gene_browser"
  name = ${?DATABASE_NAME}
  user = "postgres"
  user = ${?DATABASE_USER}
  password = "postgres"
  password = ${?DATABASE_PASSWORD}
  migrations-locations = ["db/migration"]
}

http {
  host = "0.0.0.0"
  host = ${?HTTP_HOST}
  port = 8080
  port = ${?HTTP_PORT}
}

pagination {
  base-pairs-window-size = 100000
}
