database {
  host = ${?DATABASE_HOST}
  host = "localhost"
  port = ${?DATABASE_PORT}
  port = 5432
  name = ${?DATABASE_NAME}
  name = "gene_browser"
  user = ${?DATABASE_USER}
  user = "postgres"
  password = ${?DATABASE_PASSWORD}
  password = "postgres"
  migrationsLocations = ["db/migration"]
}
